function o = CreateOdometer(name,sigma);

o = struct('Name',name,...
           'Type','Odometer',...
           'EstimatedPosition',[0 0],...
           'EstimatedHeading', 0,...
           'Sigma',sigma);