function b = CreateBrain;

%% Variables:
leftMotorSignal = 0;
rightMotorSignal = 0;
currentState = 0;
goal = [1.6000 -1.6000];
%potentialFieldFormula = @(x,y,xp,yp, alpha, beta, gamma) ...
%    alpha*exp( -((x-xp)/beta)^2  -((y-yp)/gamma)^2);
potentialFieldDiffFormulaX = @(x,y,xp,yp, alpha, beta, gamma) ...
    -(2 * alpha * (x-xp)) / (beta^2 * exp(((y-yp)/gamma)^2 ) * exp(((x-xp)/beta)^2 ));
    
potentialFieldDiffFormulaY = @(x,y,xp,yp, alpha, beta, gamma) ...
    -(2 * alpha * (y-yp)) / (gamma^2 * exp(((y-yp)/gamma)^2 ) * exp(((x-xp)/beta)^2 ));

%% Parameters:
forwardMotorSignal = 0.5;
turnMotorSignal = 0.7;
turnProbability = 0.01;
stopTurnProbability = 0.03;
leftTurnProbability = 0.50;

potentialFieldWallN = [0 1.9 10 3 0.2];%[xp, yp, alpha, beta, gamma]

potentialWallNdiffX = @(x,y) potentialFieldDiffFormulaX(x, y, potentialFieldWallN(1), potentialFieldWallN(2), ...
        potentialFieldWallN(3), potentialFieldWallN(4), potentialFieldWallN(5));
potentialWallNdiffY = @(x,y) potentialFieldDiffFormulaY(x, y, potentialFieldWallN(1), potentialFieldWallN(2), ...
        potentialFieldWallN(3), potentialFieldWallN(4), potentialFieldWallN(5));

potentialFieldCornerNW = [-1.9 1.9 5 0.3 0.3];  
potentialFieldCornerNWdiffX = @(x,y) potentialFieldDiffFormulaX(x, y, potentialFieldCornerNW(1), potentialFieldCornerNW(2), ...
        potentialFieldCornerNW(3), potentialFieldCornerNW(4), potentialFieldCornerNW(5));
potentialFieldCornerNWdiffY = @(x,y) potentialFieldDiffFormulaY(x, y, potentialFieldCornerNW(1), potentialFieldCornerNW(2), ...
        potentialFieldCornerNW(3), potentialFieldCornerNW(4), potentialFieldCornerNW(5));
potentialFieldCornerNE = [1.9 1.9 5 0.3 0.3];
potentialFieldCornerNEdiffX = @(x,y) potentialFieldDiffFormulaX(x, y, potentialFieldCornerNE(1), potentialFieldCornerNE(2), ...
        potentialFieldCornerNE(3), potentialFieldCornerNE(4), potentialFieldCornerNE(5));
potentialFieldCornerNEdiffY = @(x,y) potentialFieldDiffFormulaY(x, y, potentialFieldCornerNE(1), potentialFieldCornerNE(2), ...
        potentialFieldCornerNE(3), potentialFieldCornerNE(4), potentialFieldCornerNE(5));
potentialFieldCornerSE = [1.9 -1.9 5 0.3 0.3];   
potentialFieldCornerSEdiffX = @(x,y) potentialFieldDiffFormulaX(x, y, potentialFieldCornerSE(1), potentialFieldCornerSE(2), ...
        potentialFieldCornerSE(3), potentialFieldCornerSE(4), potentialFieldCornerSE(5));
potentialFieldCornerSEdiffY = @(x,y) potentialFieldDiffFormulaY(x, y, potentialFieldCornerNW(1), potentialFieldCornerSE(2), ...
        potentialFieldCornerSE(3), potentialFieldCornerSE(4), potentialFieldCornerSE(5));
potentialFieldCornerSW = [-1.9 -1.9 5 0.3 0.3];   
potentialFieldCornerSWdiffX = @(x,y) potentialFieldDiffFormulaX(x, y, potentialFieldCornerSW(1), potentialFieldCornerSW(2), ...
        potentialFieldCornerSW(3), potentialFieldCornerSW(4), potentialFieldCornerSW(5));
potentialFieldCornerSWdiffY = @(x,y) potentialFieldDiffFormulaY(x, y, potentialFieldCornerSW(1), potentialFieldCornerSW(2), ...
        potentialFieldCornerSW(3), potentialFieldCornerSW(4), potentialFieldCornerSW(5));
    
%syms xs;
%syms ys;
%potentialWallNx = diff(potentialFieldFormula( ...
%    xs, ys, potentialFieldWallN(1), potentialFieldWallN(2), potentialFieldWallN(3), ...
%    potentialFieldWallN(4), potentialFieldWallN(5)), xs);
%potentialWallNy = diff(potentialFieldFormula( ...
%    xs, ys, potentialFieldWallN(1), potentialFieldWallN(2), potentialFieldWallN(3), ...
%    potentialFieldWallN(4), potentialFieldWallN(5)), ys);

potentialFieldWallE = [1.9 0 10 0.2 3];
potentialWallEdiffX = @(x,y) potentialFieldDiffFormulaX(x, y, potentialFieldWallE(1), potentialFieldWallE(2), ...
        potentialFieldWallE(3), potentialFieldWallE(4), potentialFieldWallE(5));
potentialWallEdiffY = @(x,y) potentialFieldDiffFormulaY(x, y, potentialFieldWallE(1), potentialFieldWallE(2), ...
        potentialFieldWallE(3), potentialFieldWallE(4), potentialFieldWallE(5));                  
    
%potentialWallEx = @(x,y) diff(potentialFieldFormula( ...
%    x, y, potentialFieldWallE(1), potentialFieldWallE(2), potentialFieldWallE(3), ...
%    potentialFieldWallE(4), potentialFieldWallE(5)), x);
%potentialWallEy = @(x,y) diff(potentialFieldFormula( ...
%    x, y, potentialFieldWallE(1), potentialFieldWallE(2), potentialFieldWallE(3), ...
%    potentialFieldWallE(4), potentialFieldWallE(5)), y);    
    
%potentialWallE = @(x,y) potentialFieldFormula( ...
%    x, y, potentialFieldWallE(1), potentialFieldWallE(2), potentialFieldWallE(3), ...
%    potentialFieldWallE(4), potentialFieldWallE(5));
potentialFieldWallS = [0 -1.9 10 3 0.2];
potentialWallSdiffX = @(x,y) potentialFieldDiffFormulaX(x, y, potentialFieldWallS(1), potentialFieldWallS(2), ...
        potentialFieldWallS(3), potentialFieldWallS(4), potentialFieldWallS(5));
potentialWallSdiffY = @(x,y) potentialFieldDiffFormulaY(x, y, potentialFieldWallS(1), potentialFieldWallS(2), ...
        potentialFieldWallS(3), potentialFieldWallS(4), potentialFieldWallS(5)); 
    
%potentialWallSx = @(x,y) diff(potentialFieldFormula( ...
%    x, y, potentialFieldWallS(1), potentialFieldWallS(2), potentialFieldWallS(3), ...
%    potentialFieldWallS(4), potentialFieldWallS(5)), x);
%potentialWallSy = @(x,y) diff(potentialFieldFormula( ...
%    x, y, potentialFieldWallS(1), potentialFieldWallS(2), potentialFieldWallS(3), ...
%    potentialFieldWallS(4), potentialFieldWallS(5)), y);       
    
%potentialWallS = @(x,y) potentialFieldFormula( ...
%    x, y, potentialFieldWallS(1), potentialFieldWallS(2), potentialFieldWallS(3), ...
%    potentialFieldWallS(4), potentialFieldWallS(5));
potentialFieldWallW = [-1.9 0 10 0.2 3];
potentialWallWdiffX = @(x,y) potentialFieldDiffFormulaX(x, y, potentialFieldWallW(1), potentialFieldWallW(2), ...
        potentialFieldWallW(3), potentialFieldWallW(4), potentialFieldWallW(5));
potentialWallWdiffY = @(x,y) potentialFieldDiffFormulaY(x, y, potentialFieldWallW(1), potentialFieldWallW(2), ...
        potentialFieldWallW(3), potentialFieldWallW(4), potentialFieldWallW(5));
    
%potentialWallWx = @(x,y) diff(potentialFieldFormula( ...
%    x, y, potentialFieldWallW(1), potentialFieldWallW(2), potentialFieldWallW(3), ...
%    potentialFieldWallW(4), potentialFieldWallW(5)), x);
%potentialWallWy = @(x,y) diff(potentialFieldFormula( ...
%    x, y, potentialFieldWallW(1), potentialFieldWallW(2), potentialFieldWallW(3), ...
%    potentialFieldWallW(4), potentialFieldWallW(5)), y); 
    
%potentialWallW = @(x,y) potentialFieldFormula( ...
%    x, y, potentialFieldWallW(1), potentialFieldWallW(2), potentialFieldWallW(3), ...
%    potentialFieldWallW(4), potentialFieldWallW(5));
potentialFieldObjectNW = [-0.8 0.8 20 0.3 0.3];
potentialObjectNWdiffX = @(x,y) potentialFieldDiffFormulaX(x, y, potentialFieldObjectNW(1), potentialFieldObjectNW(2), ...
        potentialFieldObjectNW(3), potentialFieldObjectNW(4), potentialFieldObjectNW(5));
potentialObjectNWdiffY = @(x,y) potentialFieldDiffFormulaY(x, y, potentialFieldObjectNW(1), potentialFieldObjectNW(2), ...
        potentialFieldObjectNW(3), potentialFieldObjectNW(4), potentialFieldObjectNW(5));

% potentialObjectNWx = @(x,y) diff(potentialFieldFormula( ...
%     x, y, potentialFieldObjectNW(1), potentialFieldObjectNW(2), potentialFieldObjectNW(3), ...
%     potentialFieldObjectNW(4), potentialFieldObjectNW(5)), x);
% potentialObjectNWy = @(x,y) diff(potentialFieldFormula( ...
%     x, y, potentialFieldObjectNW(1), potentialFieldObjectNW(2), potentialFieldObjectNW(3), ...
%     potentialFieldObjectNW(4), potentialFieldObjectNW(5)), y);     
    
%potentialObjectNW = @(x,y) potentialFieldFormula( ...
%    x, y, potentialFieldObjectNW(1), potentialFieldObjectNW(2), potentialFieldObjectNW(3), ...
%    potentialFieldObjectNW(4), potentialFieldObjectNW(5));
potentialFieldObjectSE = [0.8 -0.8 20 0.3 0.3];
potentialObjectSEdiffX = @(x,y) potentialFieldDiffFormulaX(x, y, potentialFieldObjectSE(1), potentialFieldObjectSE(2), ...
        potentialFieldObjectSE(3), potentialFieldObjectSE(4), potentialFieldObjectSE(5));
potentialObjectSEdiffY = @(x,y) potentialFieldDiffFormulaY(x, y, potentialFieldObjectSE(1), potentialFieldObjectSE(2), ...
        potentialFieldObjectSE(3), potentialFieldObjectSE(4), potentialFieldObjectSE(5));
    
% potentialObjectSEx = @(x,y) diff(potentialFieldFormula( ...
%     x, y, potentialFieldObjectSE(1), potentialFieldObjectSE(2), potentialFieldObjectSE(3), ...
%     potentialFieldObjectSE(4), potentialFieldObjectSE(5)), x);
% potentialObjectSEy = @(x,y) diff(potentialFieldFormula( ...
%     x, y, potentialFieldObjectSE(1), potentialFieldObjectSE(2), potentialFieldObjectSE(3), ...
%     potentialFieldObjectSE(4), potentialFieldObjectSE(5)), y);    
% %potentialObjectSE = @(x,y) potentialFieldFormula( ...
%    x, y, potentialFieldObjectSE(1), potentialFieldObjectSE(2), potentialFieldObjectSE(3), ...
%    potentialFieldObjectSE(4), potentialFieldObjectSE(5));
potentialFieldGoal = [goal(1) goal(2) -130 5 5];
%potentialGoal = @(x,y) potentialFieldFormula( ...
%    x, y, potentialFieldGoal(1), potentialFieldGoal(2), potentialFieldGoal(3), ...
%    potentialFieldGoal(4), potentialFieldGoal(5));
potentialGoalDiffX = @(x,y) potentialFieldDiffFormulaX(x, y, potentialFieldGoal(1), potentialFieldGoal(2), ...
        potentialFieldGoal(3), potentialFieldGoal(4), potentialFieldGoal(5));
potentialGoalDiffY = @(x,y) potentialFieldDiffFormulaY(x, y, potentialFieldGoal(1), potentialFieldGoal(2), ...
        potentialFieldGoal(3), potentialFieldGoal(4), potentialFieldGoal(5));
    
% potentialGoalx = @(x,y) diff(potentialFieldFormula( ...
%     x, y, potentialFieldGoal(1), potentialFieldGoal(2), potentialFieldGoal(3), ...
%     potentialFieldGoal(4), potentialFieldGoal(5)), x);
% potentialGoaly = @(x,y) diff(potentialFieldFormula( ...
%     x, y, potentialFieldGoal(1), potentialFieldGoal(2), potentialFieldGoal(3), ...
%     potentialFieldGoal(4), potentialFieldGoal(5)), y);    

vNav = 0.5;

b = struct('LeftMotorSignal',leftMotorSignal,...
           'RightMotorSignal',rightMotorSignal,...
           'CurrentState',currentState,...
           'ForwardMotorSignal',forwardMotorSignal,...
           'TurnMotorSignal',turnMotorSignal,...
           'TurnProbability',turnProbability,...
           'StopTurnProbability',stopTurnProbability,...
           'LeftTurnProbability',leftTurnProbability, ...
           'PotentialFieldWallN', potentialFieldWallN, ...
           'PotentialWallNdiffX', potentialWallNdiffX, ...
           'PotentialWallNdiffY', potentialWallNdiffY, ...
           'PotentialFieldWallE', potentialFieldWallE, ...
           'PotentialWallEdiffX', potentialWallEdiffX, ...
           'PotentialWallEdiffY', potentialWallEdiffY, ...
           'PotentialFieldWallS', potentialFieldWallS, ...
           'PotentialWallSdiffX', potentialWallSdiffX, ...
           'PotentialWallSdiffY', potentialWallSdiffY, ...
           'PotentialFieldWallW', potentialFieldWallW, ...
           'PotentialWallWdiffX', potentialWallWdiffX, ...
           'PotentialWallWdiffY', potentialWallWdiffY, ...
           'PotentialFieldCornerNW', potentialFieldCornerNW, ...
           'PotentialFieldCornerNE', potentialFieldCornerNE, ...
           'PotentialFieldCornerSE', potentialFieldCornerSE, ...
           'PotentialFieldCornerSW', potentialFieldCornerSW, ...
           'PotentialFieldCornerNWdiffX', potentialFieldCornerNWdiffX, ...
           'PotentialFieldCornerNEdiffX', potentialFieldCornerNEdiffX, ...
           'PotentialFieldCornerSEdiffX', potentialFieldCornerSEdiffX, ...
           'PotentialFieldCornerSWdiffX', potentialFieldCornerSWdiffX, ...
           'PotentialFieldCornerNWdiffY', potentialFieldCornerNWdiffY, ...
           'PotentialFieldCornerNEdiffY', potentialFieldCornerNEdiffY, ...
           'PotentialFieldCornerSEdiffY', potentialFieldCornerSEdiffY, ...
           'PotentialFieldCornerSWdiffY', potentialFieldCornerSWdiffY, ...
           'PotentialFieldObjectNW', potentialFieldObjectNW, ...
           'PotentialObjectNWdiffX', potentialObjectNWdiffX, ...
           'PotentialObjectNWdiffY', potentialObjectNWdiffY, ...
           'PotentialFieldObjectSE', potentialFieldObjectSE, ...
           'PotentialObjectSEdiffX', potentialObjectSEdiffX, ...
           'PotentialObjectSEdiffY', potentialObjectSEdiffY, ...
           'PotentialFieldGoal', potentialFieldGoal, ...
           'PotentialGoalDiffX', potentialGoalDiffX, ...
           'PotentialGoalDiffY', potentialGoalDiffY, ...
           'VNav', vNav);