function s = CreateIRSensor(name,relativeAngle,size,numberOfRays,openingAngle,range,c1,c2,sigma);

s = struct('Name',name,...
           'Type','IR',...
           'RelativeAngle',relativeAngle,...
           'Size',size,...
           'NumberOfRays',numberOfRays,...
           'OpeningAngle',openingAngle,...
           'Range',range,...
           'C1',c1,...
           'C2',c2,...
           'Sigma',sigma,...
           'Position',[0 0],...
           'AbsoluteAngle',0,...
           'RayDirections',zeros(numberOfRays,1),...
           'RayLengths',zeros(numberOfRays,1),...
           'Reading',0);
           
