function b = CreateBrain;

%% Variables:
leftMotorSignal = 0;
rightMotorSignal = 0;
currentState = 0;

%% Parameters:
forwardMotorSignal = 0.5;
turnMotorSignal = 0.7;
turnProbability = 0.01;
stopTurnProbability = 0.03;
leftTurnProbability = 0.50;
potentialWallN = [-pi/2 1.4 0];
potentialWallE = [pi 1.4 0];
potentialWallS = [pi/2 -1.4 0];
potentialWallW = [0.0 -1.4 0];
potentialObjectNW = [pi/2 0 -pi/2 pi; ...
                    1.2 -0.4 0.4 -1.2; ...
                    0 0 0 0 ];
potentialObjectSE = [pi/2 0 -pi/2 pi; ...
                    -0.4 1.2 -1.2 0.4; ...
                    0 0 0 0 ];

potentialGoal = [1,-1];

turningAngle = 0.3;

b = struct('LeftMotorSignal',leftMotorSignal,...
           'RightMotorSignal',rightMotorSignal,...
           'CurrentState',currentState,...
           'ForwardMotorSignal',forwardMotorSignal,...
           'TurnMotorSignal',turnMotorSignal,...
           'TurnProbability',turnProbability,...
           'StopTurnProbability',stopTurnProbability,...
           'LeftTurnProbability',leftTurnProbability, ...
           'PotentialWallN', potentialWallN, ...
           'PotentialWallE', potentialWallE, ...
           'PotentialWallS', potentialWallS, ...
           'PotentialWallW', potentialWallW, ...
           'PotentialObjectNW', potentialObjectNW, ...
           'PotentialObjectSE', potentialObjectSE, ...
           'PotentialGoal', potentialGoal, ...
           'TurningAngle', turningAngle);